var N = null;var sourcesIndex = {};
sourcesIndex["rustpython"] = {"name":"","dirs":[{"name":"shell","files":["readline.rs","rustyline_helper.rs"]}],"files":["main.rs","shell.rs"]};
sourcesIndex["rustpython_bytecode"] = {"name":"","files":["bytecode.rs","lib.rs"]};
sourcesIndex["rustpython_compiler"] = {"name":"","dirs":[{"name":"peephole","files":["optimizations.rs"]}],"files":["compile.rs","error.rs","lib.rs","mode.rs","output_stream.rs","peephole.rs","symboltable.rs"]};
sourcesIndex["rustpython_derive"] = {"name":"","files":["compile_bytecode.rs","error.rs","from_args.rs","lib.rs","pyclass.rs","util.rs"]};
sourcesIndex["rustpython_parser"] = {"name":"","files":["ast.rs","error.rs","fstring.rs","function.rs","lexer.rs","lib.rs","location.rs","mode.rs","parser.rs","token.rs"]};
sourcesIndex["rustpython_vm"] = {"name":"","dirs":[{"name":"obj","files":["mod.rs","objbool.rs","objbuiltinfunc.rs","objbytearray.rs","objbyteinner.rs","objbytes.rs","objclassmethod.rs","objcode.rs","objcomplex.rs","objcoroutine.rs","objdict.rs","objellipsis.rs","objenumerate.rs","objfilter.rs","objfloat.rs","objframe.rs","objfunction.rs","objgenerator.rs","objgetset.rs","objint.rs","objiter.rs","objlist.rs","objmap.rs","objmappingproxy.rs","objmemory.rs","objmodule.rs","objnamespace.rs","objnone.rs","objobject.rs","objproperty.rs","objrange.rs","objsequence.rs","objset.rs","objslice.rs","objstaticmethod.rs","objstr.rs","objsuper.rs","objtraceback.rs","objtuple.rs","objtype.rs","objweakproxy.rs","objweakref.rs","objzip.rs"]},{"name":"stdlib","dirs":[{"name":"random","files":["mersenne.rs"]}],"files":["array.rs","ast.rs","binascii.rs","collections.rs","csv.rs","dis.rs","errno.rs","faulthandler.rs","functools.rs","hashlib.rs","imp.rs","io.rs","itertools.rs","json.rs","keyword.rs","marshal.rs","math.rs","mod.rs","multiprocessing.rs","operator.rs","os.rs","platform.rs","pwd.rs","pystruct.rs","random.rs","re.rs","select.rs","signal.rs","socket.rs","string.rs","subprocess.rs","symtable.rs","thread.rs","time_module.rs","tokenize.rs","unicodedata.rs","warnings.rs","weakref.rs","zlib.rs"]}],"files":["builtins.rs","cformat.rs","dictdatatype.rs","eval.rs","exceptions.rs","format.rs","frame.rs","frozen.rs","function.rs","import.rs","lib.rs","macros.rs","py_serde.rs","pyhash.rs","pyobject.rs","scope.rs","sequence.rs","slots.rs","sysmodule.rs","types.rs","util.rs","version.rs","vm.rs"]};
sourcesIndex["rustpython_wasm"] = {"name":"","files":["browser_module.rs","convert.rs","js_module.rs","lib.rs","vm_class.rs","wasm_builtins.rs"]};
createSourceSidebar();
